version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: monitor-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - monitor-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: monitor-redis-insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - monitor-net

networks:
  monitor-net:
    external: true
    name: monitor_monitor-net
