server:
  port: 5000

spring:
  application:
    name: monitor-backend

  # 1. Database PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/monitor_db
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver

  # 2. JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate   # Validate schema giữa Entity và DB
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

  # 3. Flyway Migration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # 4. Redis Config
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60s
      database: 0

  # 5. Redis Cache
  cache:
    type: redis
    redis:
      time-to-live: 600000ms
      cache-null-values: false

  # 6. OAuth2 Resource Server (Keycloak Integration)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/monitor-realm
          jwk-set-uri: http://localhost:8080/realms/monitor-realm/protocol/openid-connect/certs

# Cấu hình Keycloak Admin Client
keycloak:
  server-url: http://localhost:8080
  realm: monitor-realm
  admin:
    username: admin        # Username admin quản trị của Keycloak (master realm)
    password: Admin@123        # Password admin của Keycloak
    client-id: admin-cli

# Cấu hình tài khoản Admin mặc định cho ứng dụng Monitor
app:
  admin:
    username: admin
    email: admin@monitor.com
    password: Admin@123
    full-name: System Administrator
    phone: "0900000000"
    role: ROLE_SUPER_ADMIN

# 7. MyBatis Config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.monitor.backend.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 8. SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# 9. Logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    # Sửa 2 dòng này để hiện log Validate trên Spring Boot 3/4 (Hibernate 6/7)
    org.hibernate.orm.schema: TRACE
    org.hibernate.tool.schema: TRACE
    com.monitor.backend: DEBUG